name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build ${{matrix.os}}/${{matrix.build-type}}
    runs-on: ${{matrix.os}}-latest
    env:
      CODE_SIGNING_PFX_BASE64: ${{secrets.CODE_SIGNING_PFX_BASE64}}
    steps:
      - uses: actions/checkout@v2
      - name: Fetch code-signing key
        if: matrix.os == 'windows' && env.CODE_SIGNING_PFX_BASE64 != ''
        run: '[System.Convert]::FromBase64String($Env:CODE_SIGNING_PFX_BASE64) | Set-Content ${{runner.temp}}/MyCert.pfx -AsByteStream'
      - name: Make build directory
        run: cmake -E make_directory build
      - name: Configure
        working-directory: build
        shell: pwsh
        run: |
          cmake .. `
            -DCMAKE_BUILD_TYPE=${{matrix.build-type}} `
            "-DSIGNTOOL_KEY_FILE=${{runner.temp}}/MyCert.pfx" `
            "-DCMAKE_INSTALL_PREFIX=${{runner.temp}}/install"
      - name: Compile
        working-directory: build
        run: cmake --build . --config ${{matrix.build-type}} --parallel
      - name: Install
        working-directory: build
        run: cmake --install . --config ${{matrix.build-type}}
      - name: Upload MacOS Executable
        if: matrix.os == 'macos'
        uses: actions/upload-artifact@v2
        with:
          name: sddiscord-Mac-${{matrix.build-type}}
          path: build/Sources/sddiscord
      - name: Upload Windows Executable
        if: matrix.os == 'windows'
        uses: actions/upload-artifact@v2
        with:
          name: sddiscord-Windows-${{matrix.build-type}}
          path: build/Sources/${{matrix.build-type}}/sddiscord.exe
    strategy:
      matrix:
        os: [windows, macos]
        build-type: [Release, Debug]
  streamDeckPlugin:
    name: ${{matrix.build-type}} .streamDeckPlugin
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Configure
        run: |
          cmake . \
            -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
            -DCMAKE_INSTALL_PREFIX=${{runner.temp}}/com.fredemmott.discord.sdPlugin
      - name: Install static files
        working-directory: sdPlugin
        run: make install
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          path: ${{runner.temp}}/artifacts
      - name: Copy executables
        working-directory: ${{runner.temp}}
        run: |
          install -m755 \
            artifacts/sddiscord-Mac-${{matrix.build-type}}/sddiscord \
            com.fredemmott.discord.sdPlugin/sddiscord
          install -m755 \
            artifacts/sddiscord-Windows-${{matrix.build-type}}/sddiscord.exe \
            com.fredemmott.discord.sdPlugin/sddiscord.exe
      - name: Checkout DistributionTool
        uses: actions/checkout@v2
        with:
          ref: distributiontool-v1.1
      - name: Build .streamDeckPlugin
        run: |
          set +e
          ./DistributionTool -b \
            -i ${{runner.temp}}/com.fredemmott.discord.sdPlugin \
            -o .
          if [ $? -eq 0 ]; then
            echo "Distribution tool failed"
            exit 1
          else
            set -e
            test -f com.fredemmott.discord.streamDeckPlugin
          fi
      - name: Build .zip
        run: |
          zip \
          SDDiscord-${{matrix.build-type}}-${{github.sha}}-streamDeckPlugin.zip \
          com.fredemmott.discord.streamDeckPlugin
      - name: Upload Zip
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.build-type}}-StreamDeckPlugin
          path: SDDiscord-${{matrix.build-type}}-${{github.sha}}-streamDeckPlugin.zip
    strategy:
      matrix:
        build-type: [Release, Debug]
  release:
    name: Publish Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        path: ${{runner.temp}}/artifacts
    - name: Display downloaded files
      run: ls -R
      working-directory: ${{runner.temp}}/artifacts
    - name: Create Draft Release
      id: create-release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: Release ${{ steps.ref.outputs.tag }}
        tag_name: ${{steps.ref.outputs.tag}}
        draft: true
    - name: Attach Release Build
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ${{runner.temp}}/artifacts/Release-StreamDeckPlugin/com.fredemmott.micmutetoggle.streamDeckPlugin
        asset_name: com.fredemmott.micmutetoggle.streamDeckPlugin
        asset_content_type: application/octet-stream
    - name: Attach Debug Build
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ${{runner.temp}}/artifacts/Debug-StreamDeckPlugin/com.fredemmott.micmutetoggle.streamDeckPlugin
        asset_name: debug-com.fredemmott.micmutetoggle.streamDeckPlugin
        asset_content_type: application/octet-stream
