name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build (${{matrix.os}}/${{matrix.build-type}})
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make build directory
        run: cmake -E make_directory build
      - name: Configure
        working-directory: build
        run: |
          cmake .. \
            -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
            "-DCMAKE_INSTALL_PREFIX=$(echo "${{runner.temp}}/install" | tr "\\\\" /)"
        shell: bash
      - name: Compile
        working-directory: build
        run: cmake --build . --config ${{matrix.build-type}}
      - name: Install
        working-directory: build
        run: cmake --install . --config ${{matrix.build-type}}
      - name: Upload MacOS Executable
        if: matrix.os == 'macos'
        uses: actions/upload-artifact@v2
        with:
          name: sddiscord-Mac-${{matrix.build-type}}
          path: build/Sources/sddiscord
      - name: Upload Windows Executable
        if: matrix.os == 'windows'
        uses: actions/upload-artifact@v2
        with:
          name: sddiscord-Windows-${{matrix.build-type}}.exe
          path: build/Sources/${{matrix.build-type}}/sddiscord.exe
    strategy:
      matrix:
        os: [windows, macos]
        build-type: [Release, Debug]
  streamDeckPlugin:
    name: Export .streamDeckPlugin (${{matrix.build-type}})
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Configure
        run: |
          cmake . \
            -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
            -DCMAKE_INSTALL_PREFIX=${{runner.temp}}/com.fredemmott.discord.sdPlugin
      - name: Install static files
        working-directory: sdPlugin
        run: make install
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          path: ${{runner.temp}}/artifacts
      - name: Copy executables
        working-directory: ${{runner.temp}}
        run: |
          install -m755 \
            artifacts/sddiscord-Mac-${{matrix.build-type}}/sddiscord \
            com.fredemmott.sddiscord.sdPlugin/sddiscord
          install -m755 \
            artifacts/sddiscord-Windows-${{matrix.build-type}}/sddiscord.exe \
            com.fredemmott.sddiscord.sdPlugin/sddiscord.exe
      - name: Checkout DistributionTool
        uses: actions/checkout@v2
        with:
          ref: distributiontool-v1.1
      - run: ls -lR ./ ${{runner.temp}}
      - name: Build .streamDeckPlugin
        run: |
          ./DistributionTool -b \
            -i ${{runner.temp}}/com.fredemmott.discord.sdPlugin \
            -o .
      - run: ls -lR ./
      - name: Build .zip
        run: |
          zip \
          SDDiscord-${{matrix.build-type}}-${{github.sha}}-streamDeckPlugin.zip \
          com.fredemmott.sddiscord.streamDeckPlugin
      - name: Upload Zip
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.build-type}}-StreamDeckPlugin
          path: SDDiscord-${{matrix.build-type}}-${{github.sha}}-streamDeckPlugin.zip
    strategy:
      matrix:
        build-type: [Release, Debug]
